### ISSUE TITLE
Saving dictionaries can unintentionally generate invalid data files

### ISSUE THREAD

**Issue by JimmyCushnie** [JimmyCushnie/SUCC#5]
```csharp
void Test()
{
    var dicc = new Dictionary<int, Vector3>()
    {
        [22] = new Vector3(-12, 323, 432.43f),
        [55] = new Vector3(-1, 0, 100),
        [-100] = new Vector3(Mathf.PI, Mathf.PI, Mathf.PI),
    };

    var file = new DataFile("test", autoSave: true);
    file.Set("dicc boi", dicc);
}

```

That code generates this file:

```
dicc boi:
    22:
        x: -12
        y: 323
        z: 432.43
    55:
        x: -1
        y: 0
        z: 100
    -100:
        x: 3.141593
        y: 3.141593
        z: 3.141593
```

Notice the key called "-100". Keys are not allowed to begin with `-`, as that character is reserved for list nodes. Trying to read the file later will throw errors. This can also happen when using DataFile.SaveAsDictionary().

The solution is probably to allow `-` in key nodes, and determine what is a list node by the absence of `:`.
